name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           docker logout
           docker build -t nodejsapp . 
           docker tag nodejsapp:latest priyanshushriv/nodeapp_sensehawk:v1
           docker login "index.docker.io" -u priyanshushriv -p p9009039993P@
           docker push priyanshushriv/nodeapp_sensehawk:v1
