name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          COMMIT_VAR: ${{ contains(github.event.head_commit.message, '[commit var]') }}
      run: |
           docker logout
           docker build -t nodejsapp . 
           docker tag nodejsapp priyanshushriv/nodeapp_sensehawk:${COMMIT_VAR}
           docker login  -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_SECRET }} docker.io
           docker push priyanshushriv/nodeapp_sensehawk:${COMMIT_VAR}
